export  const  ALL_PRODUCTS_REQUEST='ALL_PRODUCTS_REQUEST'

export  const  ALL_PRODUCTS_SUCCESS='ALL_PRODUCTS_SUCCESS'
export  const  ALL_PRODUCTS_FAIL='ALL_PRODUCTS_FAIL'
export  const  ALL_PRODUCTS_ERRORS='ALL_PRODUCTS_ERRORS'
export  const  ALL_PRODUCTS_DETAILS_SUCCESS='ALL_PRODUCTS_DETAILS_SUCCESS'
export  const  ALL_PRODUCTS_DETAILS_FAIL='ALL_PRODUCTS_DETAILS_FAIL'
export  const  ALL_PRODUCTS_DETAILS_REQUEST='ALL_PRODUCTS_DETAILS_REQUEST'
export  const  ALL_PRODUCTS_DETAILS_ERRORS='ALL_PRODUCTS_DETAILS_ERRORS'